-- MySQL Script generated by MySQL Workbench
-- 01/27/18 12:38:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedidos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_solicitante` INT(11) NULL,
  `data_de_compra` VARCHAR(100) NULL,
  `cep` VARCHAR(10) NULL,
  `rua` VARCHAR(100) NULL,
  `numero` INT(10) NULL,
  `bairro` VARCHAR(100) NULL,
  `cidade` VARCHAR(100) NULL,
  `estado` VARCHAR(100) NULL,
  `pais` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`insumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`insumos` (
  `id` INT(11) NOT NULL,
  `id_pedido` INT(11) NULL,
  `id_material` INT(11) NULL,
  `descricao` TEXT NULL,
  `preco` FLOAT NULL,
  `quantidade` INT(10) NULL,
  `insumoscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`pedidos` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`materiais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`materiais` (
  `id` INT(11) NOT NULL,
  `id_pedido` INT(11) NULL,
  `nome` VARCHAR(255) NULL,
  `marca` VARCHAR(255) NULL,
  `preco` FLOAT NULL,
  `quantidade` INT(10) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`insumos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`solicitantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`solicitantes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `telefone` VARCHAR(100) NULL,
  `cpf` VARCHAR(20) NULL,
  `cep` VARCHAR(10) NULL,
  `rua` VARCHAR(100) NULL,
  `numero` INT(10) NULL,
  `bairro` VARCHAR(100) NULL,
  `cidade` VARCHAR(100) NULL,
  `estado` VARCHAR(100) NULL,
  `pais` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`pedidos` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
